---
apiVersion: v1
kind: Service
metadata:
  name: color
  namespace: faces
spec:
  type: ClusterIP
  selector:
    service: color
  ports:
  - port: 80
    targetPort: http
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: color-route
  namespace: faces
spec:
  parentRefs:
    - name: color
      kind: Service
      group: ""
      port: 80
  rules:
    - backendRefs:
        - name: color
          group: ""
          port: 80
          kind: Service
---
apiVersion: argoproj.io/v1alpha1
kind: Deployment
metadata:
  name: color
  namespace: faces
spec:
  replicas: 1
  selector:
    matchLabels:
      service: color
  template:
    metadata:
      labels:
        service: color
    spec:
      containers:
      - name: color
        image: ghcr.io/buoyantio/faces-workload:1.5.0
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: FACES_SERVICE
          value: "color"
        # - name: COLOR
        #   value: "blue"
        - name: DELAY_BUCKETS
          value: "0,5,10,15,20,50,200,500,750"
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 1
          periodSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 128Mi
