apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-viz
  namespace: argocd
spec:
  destination:
    namespace: linkerd-viz
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  source:
    chart: linkerd-viz
    repoURL: https://helm.linkerd.io/edge
    targetRevision: 2024.10.1
    helm:
      parameters:
      - name: dashboard.enforcedHostRegexp
        value: ".*"
